# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Parchment gives Minecraft's own code readable parameter names and javadoc while you work.
# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment Properties
# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)

## Mod Properties

mod_id=hot_peppers
mod_name=Hot Peppers
mod_license=GPL-3.0
mod_version=1.0.1
mod_group_id=com.lincstoel.hotpeppers
